// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYTY_Trw6nU6Kxiw1xnY6G4OIqJbgZ6M',
    appId: '1:798242587410:web:211e99e55abebae27029cb',
    messagingSenderId: '798242587410',
    projectId: 'planet-learning-app',
    authDomain: 'planet-learning-app.firebaseapp.com',
    storageBucket: 'planet-learning-app.firebasestorage.app',
    measurementId: 'G-C48VMKSPYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe7KGtsxVwf4QloULW37t5Nz6zpptrlcY',
    appId: '1:798242587410:android:501816601737424b7029cb',
    messagingSenderId: '798242587410',
    projectId: 'planet-learning-app',
    storageBucket: 'planet-learning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2uGnq6R-c4cRjJ3BqfdGcZtzuaZkj5k',
    appId: '1:798242587410:ios:1a9ab5f6d8d7c51a7029cb',
    messagingSenderId: '798242587410',
    projectId: 'planet-learning-app',
    storageBucket: 'planet-learning-app.firebasestorage.app',
    iosBundleId: 'com.example.planetLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2uGnq6R-c4cRjJ3BqfdGcZtzuaZkj5k',
    appId: '1:798242587410:ios:1a9ab5f6d8d7c51a7029cb',
    messagingSenderId: '798242587410',
    projectId: 'planet-learning-app',
    storageBucket: 'planet-learning-app.firebasestorage.app',
    iosBundleId: 'com.example.planetLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkYTY_Trw6nU6Kxiw1xnY6G4OIqJbgZ6M',
    appId: '1:798242587410:web:609a65e1c745a8167029cb',
    messagingSenderId: '798242587410',
    projectId: 'planet-learning-app',
    authDomain: 'planet-learning-app.firebaseapp.com',
    storageBucket: 'planet-learning-app.firebasestorage.app',
    measurementId: 'G-56DQPV8RZP',
  );
}
